spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:54032/payloads_stats_db"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "update"